plugins { id 'com.android.application' }
android {
    namespace 'com.anshify.htmlviewer'
    compileSdk 34
    defaultConfig {
        applicationId 'com.anshify.htmlviewer'
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }
    androidResources {
        noCompress 'html'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
